#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Sep 09 23:33:24 -05 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_sum1bit_behav -key {Behavioral:sim_1:Functional:tb_sum1bit} -tclbatch tb_sum1bit.tcl -log simulate.log"
xsim tb_sum1bit_behav -key {Behavioral:sim_1:Functional:tb_sum1bit} -tclbatch tb_sum1bit.tcl -log simulate.log

